---
title: "Histórico das aulas do curso"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
source("knitr_setup.R")
```

Abaixo o histórico de atividades realizadas em classe e atividades extra
classe aplicadas.

- **07/03**: Apresentação da disciplina (em função da troca de professores)
- **09/03**: Conceitos de amostragem. [Slides](01_introducao_e_amostragem/01_Introducao_a_Estatistica_e_amostragem.pdf)
- **14/03**: Classificação de variáveis. Análise exploratória de dados.
  [Material](02_Analise_Exploratoria_de_Dados.html)
- **16/03**: Análise exploratória de dados: variáveis quantitativas
  contínuas. [Material](02_Analise_Exploratoria_de_Dados.html)
- **21/03**: Sabatina 1
- **23/03**: Medidas resumo: medidas de tendência central.
  [Slides](03_Medidas_resumo/03_Medidas_resumo.pdf)
- **28/03**: Medidas resumo: medidas de variabilidade.
  [Slides](03_Medidas_resumo/03_Medidas_resumo.pdf)
- **30/03**: Medidas resumo: medidas de posição relativa.
  [Slides](03_Medidas_resumo/03_Medidas_resumo.pdf)
- **04/04**: Sabatina 2

## Exercícios

- [Lista 1][]: amostragem e análise exploratória de dados. [Gabarito 1][].
- [Lista 2][]: Medidas resumo. [Gabarito 2][]

## Notas

As notas estão disponíveis [nesta página](notas.html).



[Lista 1]: exercicios/01_Amostragem_e_Exploratoria.pdf
[Gabarito 1]: exercicios/01_Amostragem_e_Exploratoria_GABARITO.pdf
[Lista 2]: exercicios/03_Medidas_resumo.pdf
[Gabarito 2]: exercicios/03_Medidas_resumo_GABARITO.pdf
